spring:
  application:
    name: Education-Tracking-System

  #Database Configuration
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    show-sql: true

#Application Properties
super_admin:
  email: ${SUPER-ADMIN_EMAIL}